server:
  port: 8081

mybatis:
  type-aliases-package: com.cuijian.order.entity
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: orderservice
  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
